Added: Check if name of scene material is None
Adding an error message telling the user which (truncated) XML element caused the error.

Avoids throwing error ```Before, a AttributeError: 'NoneType' object has no attribute 'startswith'```

Fixed minor type.

Signed-off-by: hms0411rt <hms0411rt@users.noreply.github.com>